CREATE TABLE IF NOT EXISTS tracks (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    metadata JSONB NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NULL,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    album VARCHAR(255) NULL,
    genre VARCHAR(100) NULL,
    description VARCHAR(255) NULL,
    duration INTEGER NOT NULL,
    is_public BOOLEAN DEFAULT FALSE NOT NULL,
    play_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
